// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact = require("reason-react/src/reasonReact.js");
var Base = require("./styled/Base");
var Label = require("./styled/Label");
var TouchableOpacityRe = require("bs-react-native/src/components/touchableOpacityRe.js");

function make(children) {
  return ReasonReact.wrapJsForReason(Label.default, {}, children);
}

var Label$1 = /* module */ [/* make */ make];

function make$1(last, children) {
  return ReasonReact.wrapJsForReason(
    Base.default,
    {
      last: Js_boolean.to_js_boolean(last),
    },
    children
  );
}

var Base$1 = /* module */ [/* make */ make$1];

var Styled = /* module */ [/* Label */ Label$1, /* Base */ Base$1];

var component = ReasonReact.statelessComponent("PopupMenuOption");

function make$2(last, action, _) {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      TouchableOpacityRe.make(
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* Some */ [action.onPress],
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* Some */ [0.8],
        /* None */ 0,
        /* None */ 0
      )(
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            make$1(
              last,
              /* array */ [
                ReasonReact.element(
                  /* None */ 0,
                  /* None */ 0,
                  make(/* array */ [action.title])
                ),
              ]
            )
          ),
        ]
      )
    );
  };
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, function(jsProps) {
  return make$2(jsProps.last, jsProps.action, /* array */ []);
});

exports.Styled = Styled;
exports.component = component;
exports.make = make$2;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
