// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var TextRe = require("bs-react-native/src/components/textRe.js");
var ReasonReact = require("reason-react/src/reasonReact.js");
var DailyProgressFacetStyled = require("./styled/DailyProgressFacetStyled.bs.js");

var component = ReasonReact.statelessComponent("DailyProgressFacet");

function make(name, parentContainerWidth, _) {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      DailyProgressFacetStyled.Container[/* make */ 0](
        parentContainerWidth,
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            TextRe.Text[/* make */ 0](
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* array */ [name]
            )
          ),
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            DailyProgressFacetStyled.BarContainer[/* make */ 0](/* array */ [])
          ),
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            TextRe.Text[/* make */ 0](
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* array */ ["100"]
            )
          ),
        ]
      )
    );
  };
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, function(jsProps) {
  return make(jsProps.name, jsProps.parentContainerWidth, /* array */ []);
});

exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
