// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Label = require("./styled/Label");
var Container = require("./styled/Container");
var TouchableBase = require("./styled/TouchableBase");

function make(children) {
  return ReasonReact.wrapJsForReason(Container.default, {}, children);
}

var Container$1 = /* module */ [/* make */ make];

function make$1(onPress, disabled, children) {
  return ReasonReact.wrapJsForReason(
    TouchableBase.default,
    {
      onPress: onPress,
      disabled: Js_boolean.to_js_boolean(disabled),
    },
    children
  );
}

var TouchableBase$1 = /* module */ [/* make */ make$1];

function make$2(children) {
  return ReasonReact.wrapJsForReason(Label.default, {}, children);
}

var Label$1 = /* module */ [/* make */ make$2];

var Styled = /* module */ [
  /* Container */ Container$1,
  /* TouchableBase */ TouchableBase$1,
  /* Label */ Label$1,
];

var component = ReasonReact.statelessComponent("WorkoutCardStartButton");

function make$3(disabled, label, onPress, _) {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      make(
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            make$1(
              onPress,
              disabled,
              /* array */ [
                ReasonReact.element(
                  /* None */ 0,
                  /* None */ 0,
                  make$2(/* array */ [label])
                ),
              ]
            )
          ),
        ]
      )
    );
  };
  return newrecord;
}

exports.Styled = Styled;
exports.component = component;
exports.make = make$3;
/* component Not a pure module */
