language: node_js
os: osx
node_js:
  - "node"
before_script:
  - exp login -u $EXP_UNAME -p $EXP_PASSWORD
script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then exp p; fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then exp p --release-channel staging; fi
after_script:
- exp logout

# safelist
branches:
  only:
  - master
  - develop