// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Title = require("./Title");
var Status = require("./Status");
var Container = require("./Container");
var Bar = require("./Stats/Bar");
var ReasonReact = require("reason-react/src/reasonReact.js");
var Title$1 = require("./Stats/Title");
var Amount = require("./Stats/Amount");
var Column = require("./Stats/Column");
var Container$1 = require("./Stats/Container");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var BarContainer = require("./Stats/BarContainer");

function make(onLayout, children) {
  return ReasonReact.wrapJsForReason(
    Container.default,
    {
      onLayout: Js_null_undefined.from_opt(onLayout),
    },
    children
  );
}

var Container$2 = /* module */ [/* make */ make];

function make$1(children) {
  return ReasonReact.wrapJsForReason(Title.default, {}, children);
}

var Title$2 = /* module */ [/* make */ make$1];

function make$2(children) {
  return ReasonReact.wrapJsForReason(Status.default, {}, children);
}

var Status$1 = /* module */ [/* make */ make$2];

function make$3(parentContainerWidth, children) {
  return ReasonReact.wrapJsForReason(
    Container$1.default,
    {
      parentContainerWidth: parentContainerWidth,
    },
    children
  );
}

var Container$3 = /* module */ [/* make */ make$3];

function make$4(center, children) {
  return ReasonReact.wrapJsForReason(
    Column.default,
    {
      center: Js_null_undefined.from_opt(center),
    },
    children
  );
}

var Column$1 = /* module */ [/* make */ make$4];

function make$5(onLayout, children) {
  return ReasonReact.wrapJsForReason(
    BarContainer.default,
    {
      onLayout: Js_null_undefined.from_opt(onLayout),
    },
    children
  );
}

var BarContainer$1 = /* module */ [/* make */ make$5];

function make$6(width, children) {
  return ReasonReact.wrapJsForReason(
    Bar.default,
    {
      width: width,
    },
    children
  );
}

var Bar$1 = /* module */ [/* make */ make$6];

function make$7(children) {
  return ReasonReact.wrapJsForReason(Title$1.default, {}, children);
}

var Title$3 = /* module */ [/* make */ make$7];

function make$8(children) {
  return ReasonReact.wrapJsForReason(Amount.default, {}, children);
}

var Amount$1 = /* module */ [/* make */ make$8];

var Stats = /* module */ [
  /* Container */ Container$3,
  /* Column */ Column$1,
  /* BarContainer */ BarContainer$1,
  /* Bar */ Bar$1,
  /* Title */ Title$3,
  /* Amount */ Amount$1,
];

exports.Container = Container$2;
exports.Title = Title$2;
exports.Status = Status$1;
exports.Stats = Stats;
/* ./Title Not a pure module */
