// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Title = require("./Title");
var Container = require("./Container");
var ReasonReact = require("reason-react/src/reasonReact.js");

function make(children) {
  return ReasonReact.wrapJsForReason(Container.default, {}, children);
}

var Container$1 = /* module */ [/* make */ make];

function make$1(children) {
  return ReasonReact.wrapJsForReason(Title.default, {}, children);
}

var Title$1 = /* module */ [/* make */ make$1];

exports.Container = Container$1;
exports.Title = Title$1;
/* ./Title Not a pure module */
