// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var NPMBindings = require("../../config/NPMBindings.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var DailyProgress = require("./components/DailyProgress/DailyProgress.bs.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var Dimensions$BsReactNative = require("bs-react-native/src/dimensions.js");
var ScrollView$BsReactNative = require("bs-react-native/src/components/scrollView.js");

var component = ReasonReact.statelessComponent("CalendarScreen");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      ScrollView$BsReactNative.make(
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* Some */ [
          Style$BsReactNative.style(
            /* :: */ [
              Style$BsReactNative.flexGrow(1),
              /* :: */ [
                Style$BsReactNative.paddingVertical(/* Pt */ Block.__(0, [16])),
                /* :: */ [
                  Style$BsReactNative.alignItems(/* Center */ 2),
                  /* [] */ 0,
                ],
              ],
            ]
          ),
        ],
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* Some */ [/* false */ 0],
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0
      )(
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            Curry.app(NPMBindings.RNCalendars[/* Calendar */ 0][/* make */ 0], [
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* Some */ [
                Style$BsReactNative.style(
                  /* :: */ [
                    Style$BsReactNative.width(
                      /* Pt */ Block.__(0, [
                        (Dimensions$BsReactNative.get(/* window */ -762539024)
                          .width -
                          32) |
                          0,
                      ])
                    ),
                    /* :: */ [Style$BsReactNative.flex(0), /* [] */ 0],
                  ]
                ),
              ],
              /* None */ 0,
              /* array */ [],
            ])
          ),
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            DailyProgress.make(/* array */ [])
          ),
        ]
      )
    );
  };
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, function() {
  return make(/* array */ []);
});

exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
