// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Curry = require("bs-platform/lib/js/curry.js");
var StyleRe = require("bs-react-native/src/styleRe.js");
var NPMBindings = require("../../config/NPMBindings.bs.js");
var ReasonReact = require("reason-react/src/reasonReact.js");
var DimensionsRe = require("bs-react-native/src/dimensionsRe.js");
var ScrollViewRe = require("bs-react-native/src/components/scrollViewRe.js");
var DailyProgress = require("./components/DailyProgress/DailyProgress.bs.js");

var component = ReasonReact.statelessComponent("CalendarScreen");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      ScrollViewRe.ScrollView[/* make */ 2](
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* Some */ [
          StyleRe.style(
            /* :: */ [
              StyleRe.flexGrow(1),
              /* :: */ [
                StyleRe.paddingVertical(16),
                /* :: */ [
                  StyleRe.alignItems(/* center */ 98248149),
                  /* [] */ 0,
                ],
              ],
            ]
          ),
        ],
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* Some */ [/* false */ 0],
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0
      )(
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            Curry.app(NPMBindings.RNCalendars[/* Calendar */ 0][/* make */ 0], [
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* Some */ [
                StyleRe.style(
                  /* :: */ [
                    StyleRe.width(
                      (DimensionsRe.get(/* window */ -762539024).width - 32) | 0
                    ),
                    /* :: */ [StyleRe.flex(0), /* [] */ 0],
                  ]
                ),
              ],
              /* None */ 0,
              /* array */ [],
            ])
          ),
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            DailyProgress.make(/* array */ [])
          ),
        ]
      )
    );
  };
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, function() {
  return make(/* array */ []);
});

exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
