// flow-typed signature: 1b82ad18f19ae4a25b454b20f574b8d9
// flow-typed version: <<STUB>>/eslint-config-universe_v^1.0.6/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-universe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "eslint-config-universe" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "eslint-config-universe/default" {
  declare module.exports: any;
}

declare module "eslint-config-universe/native" {
  declare module.exports: any;
}

declare module "eslint-config-universe/node" {
  declare module.exports: any;
}

declare module "eslint-config-universe/shared/core" {
  declare module.exports: any;
}

declare module "eslint-config-universe/shared/prettier" {
  declare module.exports: any;
}

declare module "eslint-config-universe/shared/react" {
  declare module.exports: any;
}

declare module "eslint-config-universe/shared/readPrettierConfig" {
  declare module.exports: any;
}

declare module "eslint-config-universe/web" {
  declare module.exports: any;
}

// Filename aliases
declare module "eslint-config-universe/default.js" {
  declare module.exports: $Exports<"eslint-config-universe/default">;
}
declare module "eslint-config-universe/native.js" {
  declare module.exports: $Exports<"eslint-config-universe/native">;
}
declare module "eslint-config-universe/node.js" {
  declare module.exports: $Exports<"eslint-config-universe/node">;
}
declare module "eslint-config-universe/shared/core.js" {
  declare module.exports: $Exports<"eslint-config-universe/shared/core">;
}
declare module "eslint-config-universe/shared/prettier.js" {
  declare module.exports: $Exports<"eslint-config-universe/shared/prettier">;
}
declare module "eslint-config-universe/shared/react.js" {
  declare module.exports: $Exports<"eslint-config-universe/shared/react">;
}
declare module "eslint-config-universe/shared/readPrettierConfig.js" {
  declare module.exports: $Exports<
    "eslint-config-universe/shared/readPrettierConfig"
  >;
}
declare module "eslint-config-universe/web.js" {
  declare module.exports: $Exports<"eslint-config-universe/web">;
}
