// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Timer = require("./components/Timer/Timer.bs.js");
var Assets = require("Assets");
var Colors = require("../../config/Colors.bs.js");
var Routines = require("../../config/Routines.bs.js");
var Reductive = require("reductive/src/reductive.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Progenitor = require("../../state/Progenitor.bs.js");
var NPMBindings = require("../../config/NPMBindings.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ActionButton = require("./components/ActionButton/ActionButton.bs.js");
var SessionControl = require("./components/SessionControl/SessionControl.bs.js");
var Alert$BsReactNative = require("bs-react-native/src/alert.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var ScrollView$BsReactNative = require("bs-react-native/src/components/scrollView.js");
var Image = require("./components/styled/Image");
var SetReps = require("./components/styled/SetReps");
var SetType = require("./components/styled/SetType");
var Progress = require("./components/styled/Progress");
var Container = require("./components/styled/Container");
var Background = require("./components/styled/Background");
var Group = require("./components/SessionControl/styled/Group");

function make(children) {
  return ReasonReact.wrapJsForReason(Background.default, {}, children);
}

var Background$1 = /* module */ [/* make */ make];

function make$1(children) {
  return ReasonReact.wrapJsForReason(Container.default, {}, children);
}

var Container$1 = /* module */ [/* make */ make$1];

function make$2(children) {
  return ReasonReact.wrapJsForReason(Progress.default, {}, children);
}

var Progress$1 = /* module */ [/* make */ make$2];

function make$3(children) {
  return ReasonReact.wrapJsForReason(SetType.default, {}, children);
}

var SetType$1 = /* module */ [/* make */ make$3];

function make$4(children) {
  return ReasonReact.wrapJsForReason(SetReps.default, {}, children);
}

var SetReps$1 = /* module */ [/* make */ make$4];

function make$5(children) {
  return ReasonReact.wrapJsForReason(Group.default, {}, children);
}

var SessionControlGroup = /* module */ [/* make */ make$5];

function make$6(source, resizeMode, children) {
  return ReasonReact.wrapJsForReason(
    Image.default,
    {
      source: source,
      resizeMode: resizeMode,
    },
    children
  );
}

var Image$1 = /* module */ [/* make */ make$6];

var Styled = /* module */ [
  /* Background */ Background$1,
  /* Container */ Container$1,
  /* Progress */ Progress$1,
  /* SetType */ SetType$1,
  /* SetReps */ SetReps$1,
  /* SessionControlGroup */ SessionControlGroup,
  /* Image */ Image$1,
];

var transitionLayout = /* int array */ [
  /* Image */ 0,
  /* Progress */ 1,
  /* SetInfo */ 2,
];

var sessionLayout = /* int array */ [
  /* SetInfo */ 2,
  /* Timer */ 4,
  /* Progress */ 1,
  /* SessionControls */ 3,
];

function startTimer(self) {
  return setInterval(
    Curry._1(self[/* reduce */ 1], function() {
      return /* Tick */ 0;
    }),
    1000
  );
}

function currentExercise(s) {
  if (
    s[/* currentWorkout */ 0][/* setsCompleted */ 4][/* pushUps */ 0] <
    Caml_array.caml_array_get(
      Routines.variations,
      s[/* currentWorkout */ 0][/* level */ 0]
    )[/* pushUps */ 0][/* sets */ 0]
  ) {
    return /* PushUps */ 0;
  } else if (
    s[/* currentWorkout */ 0][/* setsCompleted */ 4][/* sitUps */ 1] <
    Caml_array.caml_array_get(
      Routines.variations,
      s[/* currentWorkout */ 0][/* level */ 0]
    )[/* sitUps */ 1][/* sets */ 0]
  ) {
    return /* SitUps */ 1;
  } else if (
    s[/* currentWorkout */ 0][/* setsCompleted */ 4][/* squats */ 2] <
    Caml_array.caml_array_get(
      Routines.variations,
      s[/* currentWorkout */ 0][/* level */ 0]
    )[/* squats */ 2][/* sets */ 0]
  ) {
    return /* Squats */ 2;
  } else {
    return /* Running */ 3;
  }
}

var baseComponent = ReasonReact.reducerComponent("WorkoutScreenBase");

function baseMake(navigation, reductiveState, dispatch, _) {
  var newrecord = baseComponent.slice();
  newrecord[/* willReceiveProps */ 3] = function(self) {
    var init = self[/* state */ 2];
    return /* record */ [
      /* timer */ init[/* timer */ 0],
      /* inSession */ init[/* inSession */ 1],
      /* currentExercise */ currentExercise(reductiveState),
    ];
  };
  newrecord[/* willUnmount */ 6] = function(self) {
    var match = self[/* state */ 2][/* timer */ 0][/* handle */ 1];
    if (match) {
      clearInterval(match[0]);
      return /* () */ 0;
    } else {
      return /* () */ 0;
    }
  };
  newrecord[/* render */ 9] = function(self) {
    var match = self[/* state */ 2][/* inSession */ 1];
    var layout = match !== 0 ? sessionLayout : transitionLayout;
    var match$1 = self[/* state */ 2][/* inSession */ 1];
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      make(
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            ScrollView$BsReactNative.make(
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* Some */ [
                Style$BsReactNative.style(
                  /* :: */ [Style$BsReactNative.flexGrow(1), /* [] */ 0]
                ),
              ],
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* Some */ [/* false */ 0],
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* Some */ [/* false */ 0],
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0,
              /* None */ 0
            )(
              /* array */ [
                ReasonReact.element(
                  /* None */ 0,
                  /* None */ 0,
                  make$1(
                    /* array */ [
                      ReasonReact.element(
                        /* None */ 0,
                        /* None */ 0,
                        Curry._1(
                          NPMBindings.Expo[/* KeepAwake */ 4][/* make */ 0],
                          /* array */ []
                        )
                      ),
                      $$Array.mapi(function(i, it) {
                        switch (it) {
                          case 0:
                            var match =
                              self[/* state */ 2][/* currentExercise */ 2];
                            var tmp;
                            switch (match) {
                              case 0:
                                tmp = Assets.Illustrations.pushups;
                                break;
                              case 1:
                                tmp = Assets.Illustrations.situps;
                                break;
                              case 2:
                                tmp = Assets.Illustrations.squats;
                                break;
                              case 3:
                                tmp = Assets.Illustrations.run;
                                break;
                            }
                            return ReasonReact.element(
                              /* Some */ [Pervasives.string_of_int(i)],
                              /* None */ 0,
                              make$6(tmp, "cover", /* array */ [])
                            );
                          case 1:
                            var match$1 = +(
                              self[/* state */ 2][/* currentExercise */ 2] ===
                              /* Running */ 3
                            );
                            if (match$1 !== 0) {
                              return null;
                            } else {
                              var match$2 =
                                self[/* state */ 2][/* currentExercise */ 2];
                              var tmp$1;
                              switch (match$2) {
                                case 0:
                                  tmp$1 =
                                    (reductiveState[/* currentWorkout */ 0][/* setsCompleted */ 4][/* pushUps */ 0] +
                                      1) |
                                    0;
                                  break;
                                case 1:
                                  tmp$1 =
                                    (reductiveState[/* currentWorkout */ 0][/* setsCompleted */ 4][/* sitUps */ 1] +
                                      1) |
                                    0;
                                  break;
                                case 2:
                                  tmp$1 =
                                    (reductiveState[/* currentWorkout */ 0][/* setsCompleted */ 4][/* squats */ 2] +
                                      1) |
                                    0;
                                  break;
                                case 3:
                                  tmp$1 = 1;
                                  break;
                              }
                              var match$3 =
                                self[/* state */ 2][/* currentExercise */ 2];
                              var tmp$2;
                              switch (match$3) {
                                case 0:
                                  tmp$2 = Caml_array.caml_array_get(
                                    Routines.variations,
                                    reductiveState[/* currentWorkout */ 0][/* level */ 0]
                                  )[/* pushUps */ 0][/* sets */ 0];
                                  break;
                                case 1:
                                  tmp$2 = Caml_array.caml_array_get(
                                    Routines.variations,
                                    reductiveState[/* currentWorkout */ 0][/* level */ 0]
                                  )[/* sitUps */ 1][/* sets */ 0];
                                  break;
                                case 2:
                                  tmp$2 = Caml_array.caml_array_get(
                                    Routines.variations,
                                    reductiveState[/* currentWorkout */ 0][/* level */ 0]
                                  )[/* squats */ 2][/* sets */ 0];
                                  break;
                                case 3:
                                  tmp$2 = 1;
                                  break;
                              }
                              return ReasonReact.element(
                                /* Some */ [Pervasives.string_of_int(i)],
                                /* None */ 0,
                                make$2(
                                  /* array */ [
                                    "set " +
                                      (Pervasives.string_of_int(tmp$1) +
                                        (" of " +
                                          (Pervasives.string_of_int(tmp$2) +
                                            ""))),
                                  ]
                                )
                              );
                            }
                            break;
                          case 2:
                            var match$4 = +(
                              self[/* state */ 2][/* currentExercise */ 2] ===
                              /* Running */ 3
                            );
                            var match$5 =
                              self[/* state */ 2][/* currentExercise */ 2];
                            var tmp$3;
                            switch (match$5) {
                              case 0:
                                tmp$3 = "push-ups";
                                break;
                              case 1:
                                tmp$3 = "sit-ups";
                                break;
                              case 2:
                                tmp$3 = "squats";
                                break;
                              case 3:
                                tmp$3 = "run";
                                break;
                            }
                            return ReasonReact.element(
                              /* Some */ [Pervasives.string_of_int(i)],
                              /* None */ 0,
                              make$3(
                                /* array */ [
                                  ReasonReact.element(
                                    /* None */ 0,
                                    /* None */ 0,
                                    make$4(
                                      /* array */ [
                                        match$4 !== 0
                                          ? Pervasives.string_of_int(
                                              Caml_array.caml_array_get(
                                                Routines.variations,
                                                reductiveState[/* currentWorkout */ 0][/* level */ 0]
                                              )[/* run */ 3][/* distance */ 0]
                                            ) +
                                            Caml_array.caml_array_get(
                                              Routines.variations,
                                              reductiveState[/* currentWorkout */ 0][/* level */ 0]
                                            )[/* run */ 3][/* units */ 1]
                                          : Pervasives.string_of_int(
                                              Caml_array.caml_array_get(
                                                Routines.variations,
                                                reductiveState[/* currentWorkout */ 0][/* level */ 0]
                                              )[/* sitUps */ 1][/* reps */ 1]
                                            ),
                                      ]
                                    )
                                  ),
                                  " " + tmp$3,
                                ]
                              )
                            );
                          case 3:
                            var match$6 =
                              self[/* state */ 2][/* timer */ 0][/* status */ 2];
                            var match$7 =
                              self[/* state */ 2][/* timer */ 0][/* status */ 2];
                            return ReasonReact.element(
                              /* Some */ [Pervasives.string_of_int(i)],
                              /* None */ 0,
                              make$5(
                                /* array */ [
                                  ReasonReact.element(
                                    /* None */ 0,
                                    /* None */ 0,
                                    SessionControl.make(
                                      match$6 !== -276545362
                                        ? match$6 >= 373703110
                                          ? Curry._1(
                                              self[/* reduce */ 1],
                                              function() {
                                                return /* PauseTimer */ 2;
                                              }
                                            )
                                          : Curry._1(
                                              self[/* reduce */ 1],
                                              function() {
                                                return /* StartTimer */ Block.__(
                                                  0,
                                                  [
                                                    /* Some */ [
                                                      startTimer(self),
                                                    ],
                                                  ]
                                                );
                                              }
                                            )
                                        : Curry._1(
                                            self[/* reduce */ 1],
                                            function() {
                                              return /* ResumeTimer */ 3;
                                            }
                                          ),
                                      match$7 !== -276545362
                                        ? match$7 >= 373703110
                                          ? "PAUSE"
                                          : "START"
                                        : "RESUME",
                                      Colors.blueLeftUsTooSoon,
                                      /* array */ []
                                    )
                                  ),
                                  ReasonReact.element(
                                    /* None */ 0,
                                    /* None */ 0,
                                    SessionControl.make(
                                      Curry._1(
                                        self[/* reduce */ 1],
                                        function() {
                                          var match =
                                            self[/* state */ 2][/* timer */ 0][/* handle */ 1];
                                          if (match) {
                                            clearInterval(match[0]);
                                          }
                                          return /* StopTimer */ Block.__(1, [
                                            /* None */ 0,
                                          ]);
                                        }
                                      ),
                                      "STOP",
                                      Colors.bRED,
                                      /* array */ []
                                    )
                                  ),
                                ]
                              )
                            );
                          case 4:
                            return ReasonReact.element(
                              /* Some */ [Pervasives.string_of_int(i)],
                              /* None */ 0,
                              Timer.make(
                                self[/* state */ 2][/* timer */ 0][/* timeUsed */ 0],
                                /* array */ []
                              )
                            );
                        }
                      }, layout),
                      ReasonReact.element(
                        /* None */ 0,
                        /* None */ 0,
                        ActionButton.make(
                          Curry._1(self[/* reduce */ 1], function() {
                            if (self[/* state */ 2][/* inSession */ 1]) {
                              var match =
                                self[/* state */ 2][/* timer */ 0][/* handle */ 1];
                              if (match) {
                                clearInterval(match[0]);
                              } else {
                                Curry._2(
                                  self[/* reduce */ 1],
                                  function() {
                                    return /* StopTimer */ Block.__(1, [
                                      /* None */ 0,
                                    ]);
                                  },
                                  /* () */ 0
                                );
                              }
                              Curry._1(
                                dispatch,
                                /* CompleteSet */ Block.__(1, [
                                  self[/* state */ 2][/* currentExercise */ 2],
                                  self[/* state */ 2][/* timer */ 0][/* timeUsed */ 0],
                                ])
                              );
                              if (
                                self[/* state */ 2][/* currentExercise */ 2] ===
                                /* Running */ 3
                              ) {
                                Curry._1(dispatch, /* CompleteWorkout */ 4);
                                Alert$BsReactNative.alert(
                                  "Congrats!",
                                  /* Some */ [
                                    "You've completed today's workout. Rock on!",
                                  ],
                                  /* None */ 0,
                                  /* None */ 0,
                                  /* None */ 0,
                                  /* () */ 0
                                );
                                navigation.goBack();
                              }
                            } else {
                              Curry._2(
                                self[/* reduce */ 1],
                                function() {
                                  return /* StartTimer */ Block.__(0, [
                                    /* Some */ [startTimer(self)],
                                  ]);
                                },
                                /* () */ 0
                              );
                            }
                            return /* ToggleSession */ 1;
                          }),
                          match$1 !== 0 ? "COMPLETE" : "GO",
                          /* array */ []
                        )
                      ),
                    ]
                  )
                ),
              ]
            )
          ),
        ]
      )
    );
  };
  newrecord[/* initialState */ 10] = function() {
    return /* record */ [
      /* timer : record */ [
        /* timeUsed */ 0,
        /* handle : None */ 0,
        /* status : active */ 373703110,
      ],
      /* inSession : false */ 0,
      /* currentExercise */ currentExercise(reductiveState),
    ];
  };
  newrecord[/* reducer */ 12] = function(action, state) {
    if (typeof action === "number") {
      switch (action) {
        case 0:
          if (
            state[/* timer */ 0][/* status */ 2] !== /* paused */ -276545362
          ) {
            var init = state[/* timer */ 0];
            return /* Update */ Block.__(0, [
              /* record */ [
                /* timer : record */ [
                  /* timeUsed */ (state[/* timer */ 0][/* timeUsed */ 0] + 1) |
                    0,
                  /* handle */ init[/* handle */ 1],
                  /* status */ init[/* status */ 2],
                ],
                /* inSession */ state[/* inSession */ 1],
                /* currentExercise */ state[/* currentExercise */ 2],
              ],
            ]);
          } else {
            return /* NoUpdate */ 0;
          }
          break;
        case 1:
          return /* Update */ Block.__(0, [
            /* record */ [
              /* timer */ state[/* timer */ 0],
              /* inSession */ 1 - state[/* inSession */ 1],
              /* currentExercise */ state[/* currentExercise */ 2],
            ],
          ]);
        case 2:
          var init$1 = state[/* timer */ 0];
          return /* Update */ Block.__(0, [
            /* record */ [
              /* timer : record */ [
                /* timeUsed */ init$1[/* timeUsed */ 0],
                /* handle */ init$1[/* handle */ 1],
                /* status : paused */ -276545362,
              ],
              /* inSession */ state[/* inSession */ 1],
              /* currentExercise */ state[/* currentExercise */ 2],
            ],
          ]);
        case 3:
          var init$2 = state[/* timer */ 0];
          return /* Update */ Block.__(0, [
            /* record */ [
              /* timer : record */ [
                /* timeUsed */ init$2[/* timeUsed */ 0],
                /* handle */ init$2[/* handle */ 1],
                /* status : active */ 373703110,
              ],
              /* inSession */ state[/* inSession */ 1],
              /* currentExercise */ state[/* currentExercise */ 2],
            ],
          ]);
      }
    } else if (action.tag) {
      var init$3 = state[/* timer */ 0];
      return /* Update */ Block.__(0, [
        /* record */ [
          /* timer : record */ [
            /* timeUsed */ init$3[/* timeUsed */ 0],
            /* handle */ action[0],
            /* status : stopped */ -1016999411,
          ],
          /* inSession */ state[/* inSession */ 1],
          /* currentExercise */ state[/* currentExercise */ 2],
        ],
      ]);
    } else {
      return /* Update */ Block.__(0, [
        /* record */ [
          /* timer : record */ [
            /* timeUsed */ 0,
            /* handle */ action[0],
            /* status : active */ 373703110,
          ],
          /* inSession */ state[/* inSession */ 1],
          /* currentExercise */ state[/* currentExercise */ 2],
        ],
      ]);
    }
  };
  return newrecord;
}

var make$7 = Reductive.Provider[/* createMake */ 0](
  /* None */ 0,
  Progenitor.store
);

var Provider = /* module */ [/* make */ make$7];

var component = ReasonReact.statelessComponent("WorkoutScreen");

function make$8(navigation, _) {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      Curry._2(
        make$7,
        function(param, param$1, param$2) {
          return baseMake(navigation, param, param$1, param$2);
        },
        /* array */ []
      )
    );
  };
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, function(jsProps) {
  return make$8(jsProps.navigation, /* array */ []);
});

exports.Styled = Styled;
exports.transitionLayout = transitionLayout;
exports.sessionLayout = sessionLayout;
exports.startTimer = startTimer;
exports.currentExercise = currentExercise;
exports.baseComponent = baseComponent;
exports.baseMake = baseMake;
exports.Provider = Provider;
exports.component = component;
exports.make = make$8;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* baseComponent Not a pure module */
