// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Assets = require("Assets");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Base = require("./styled/Base");
var Icon = require("./styled/Icon");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function make(source, resizeMode, children) {
  return ReasonReact.wrapJsForReason(
    Icon.default,
    {
      source: Js_null_undefined.from_opt(source),
      resizeMode: Js_null_undefined.from_opt(resizeMode),
    },
    children
  );
}

var Icon$1 = /* module */ [/* make */ make];

function make$1(children) {
  return ReasonReact.wrapJsForReason(Base.default, {}, children);
}

var Base$1 = /* module */ [/* make */ make$1];

var Styled = /* module */ [/* Icon */ Icon$1, /* Base */ Base$1];

var component = ReasonReact.statelessComponent("OverflowButton");

function make$2() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      make$1(
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            make(
              /* Some */ [Assets.Icons.chevronDown],
              /* Some */ ["contain"],
              /* array */ []
            )
          ),
        ]
      )
    );
  };
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, function() {
  return make$2(/* array */ []);
});

exports.Styled = Styled;
exports.component = component;
exports.make = make$2;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
