// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Curry = require("bs-platform/lib/js/curry.js");
var NPMBindings = require("../../../../../config/NPMBindings.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Base = require("./styled/Base");

function make(children) {
  return ReasonReact.wrapJsForReason(Base.default, {}, children);
}

var Base$1 = /* module */ [/* make */ make];

var Styled = /* module */ [/* Base */ Base$1];

var component = ReasonReact.statelessComponent("OverflowButton");

function make$1() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      make(
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            Curry._4(
              NPMBindings.VectorIcons[/* Feather */ 0][/* make */ 0],
              "chevron-down",
              18,
              "white",
              /* array */ []
            )
          ),
        ]
      )
    );
  };
  return newrecord;
}

exports.Styled = Styled;
exports.component = component;
exports.make = make$1;
/* component Not a pure module */
