// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/reasonReact.js");
var DailyProgressFacet = require("./Facet/DailyProgressFacet.bs.js");
var DailyProgressStyled = require("./styled/DailyProgressStyled.bs.js");

var component = ReasonReact.reducerComponent("DailyProgress");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function(self) {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      DailyProgressStyled.Container[/* make */ 0](
        /* Some */ [
          Curry._1(self[/* reduce */ 3], function($$event) {
            return /* MeasureContainerWidth */ [
              $$event.nativeEvent.layout.width,
            ];
          }),
        ],
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            DailyProgressStyled.Title[/* make */ 0](
              /* array */ ["today's workout"]
            )
          ),
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            DailyProgressStyled.Status[/* make */ 0](
              /* array */ ["75% complete"]
            )
          ),
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            DailyProgressFacet.make(
              "push-ups",
              self[/* state */ 4][/* containerWidth */ 0],
              /* array */ []
            )
          ),
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            DailyProgressFacet.make(
              "sit-ups",
              self[/* state */ 4][/* containerWidth */ 0],
              /* array */ []
            )
          ),
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            DailyProgressFacet.make(
              "squats",
              self[/* state */ 4][/* containerWidth */ 0],
              /* array */ []
            )
          ),
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            DailyProgressFacet.make(
              "running",
              self[/* state */ 4][/* containerWidth */ 0],
              /* array */ []
            )
          ),
        ]
      )
    );
  };
  newrecord[/* initialState */ 10] = function() {
    return /* record */ [/* containerWidth */ 0];
  };
  newrecord[/* reducer */ 12] = function(action, _) {
    return /* Update */ Block.__(0, [
      /* record */ [/* containerWidth */ action[0]],
    ]);
  };
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, function() {
  return make(/* array */ []);
});

exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
