// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Assets = require("Assets");
var ReasonReact = require("reason-react/src/reasonReact.js");
var InfoScreenStyled = require("./styled/InfoScreenStyled.bs.js");

var component = ReasonReact.statelessComponent("InfoScreen");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      InfoScreenStyled.Container[/* make */ 0](
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            InfoScreenStyled.HeroImage[/* make */ 0](
              Assets.Illustrations.theSecretSauce,
              "cover",
              /* array */ []
            )
          ),
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            InfoScreenStyled.TextContentContainer[/* make */ 0](
              /* array */ [
                ReasonReact.element(
                  /* None */ 0,
                  /* None */ 0,
                  InfoScreenStyled.Title[/* make */ 0](
                    /* array */ ["What is Saitama's secret?"]
                  )
                ),
                ReasonReact.element(
                  /* None */ 0,
                  /* None */ 0,
                  InfoScreenStyled.Description[/* make */ 0](
                    /* array */ [
                      "Lorem ipsum dolor sit amet, quidam corrumpit ad eam, duo graeco nostrud temporibus in. His suas veritus mentitum eu, in debet dicant vidisse sit. Oratio splendide vim ei, quaeque assentior sit ex, cibo clita ne sit. Exerci impedit no ius. Quidam regione consetetur cu vel. Vix ei dolor veniam periculis, porro luptatum an vel, ea eum blandit instructior.",
                    ]
                  )
                ),
              ]
            )
          ),
        ]
      )
    );
  };
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, function() {
  return make(/* array */ []);
});

exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
