// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Curry = require("bs-platform/lib/js/curry.js");
var Assets = require("Assets");
var StyleRe = require("bs-react-native/src/styleRe.js");
var ReactNative = require("bs-react-native/src/reactNative.js");
var ReasonReact = require("reason-react/src/reasonReact.js");
var HeroImage = require("./styled/HeroImage");

function make(source, resizeMode, children) {
  return ReasonReact.wrapJsForReason(
    HeroImage.default,
    {
      source: source,
      resizeMode: resizeMode,
    },
    children
  );
}

var HeroImage$1 = /* module */ [/* make */ make];

var component = ReasonReact.statelessComponent("InfoScreen");

function make$1() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      Curry.app(ReactNative.View[/* make */ 0], [
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* Some */ [
          StyleRe.style(
            /* :: */ [
              StyleRe.flex(1),
              /* :: */ [StyleRe.backgroundColor("white"), /* [] */ 0],
            ]
          ),
        ],
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* None */ 0,
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            make(Assets.Illustrations.theSecretSauce, "cover", /* array */ [])
          ),
        ],
      ])
    );
  };
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, function() {
  return make$1(/* array */ []);
});

exports.HeroImage = HeroImage$1;
exports.component = component;
exports.make = make$1;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
