// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var purpp = "#42002F";

var halfWhite = "rgba(2555, 255, 255, 0.5)";

var twentyWhite = "rgba(2555, 255, 255, 0.2)";

var fiftyWhite = "rgba(2555, 255, 255, 0.5)";

var seventyWhite = "rgba(2555, 255, 255, 0.7)";

var offWhite = "#E0E0E0";

var offYellow = "#FFFEEC";

var spotiBlack = "#191414";

var fortyBlack = "rgba(0, 0, 0, 0.4)";

var twentyBlack = "rgba(0, 0, 0, 0.2)";

var halfBlack = "rgba(0, 0, 0, 0.5)";

var heavenBlue = "#2DBDDA";

var froggo = "#39B822";

var status = "#651FFF";

var start = "#1DE9B6";

var bRED = "#FF5252";

var twentyOnStart = "#61F0CC";

var blueLeftUsTooSoon = "#536DFE";

var disabled = "#9E9E9E";

exports.purpp = purpp;
exports.halfWhite = halfWhite;
exports.twentyWhite = twentyWhite;
exports.fiftyWhite = fiftyWhite;
exports.seventyWhite = seventyWhite;
exports.offWhite = offWhite;
exports.offYellow = offYellow;
exports.spotiBlack = spotiBlack;
exports.fortyBlack = fortyBlack;
exports.twentyBlack = twentyBlack;
exports.halfBlack = halfBlack;
exports.heavenBlue = heavenBlue;
exports.froggo = froggo;
exports.status = status;
exports.start = start;
exports.bRED = bRED;
exports.twentyOnStart = twentyOnStart;
exports.blueLeftUsTooSoon = blueLeftUsTooSoon;
exports.disabled = disabled;
/* No side effect */
