// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Expo = require("expo");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var VectorIcons = require("@expo/vector-icons");
var Ticker = require("../components/Ticker");
var ReactNativeCalendars = require("react-native-calendars");
var ReactNativeModalDatetimePicker = require("react-native-modal-datetime-picker");

function make(
  minDate,
  onDayPress,
  hideArrows,
  monthFormat,
  onMonthChange,
  hideExtraDays,
  disableMonthChange,
  firstDay,
  hideDayNames,
  markedDates,
  style,
  markingType,
  children
) {
  return ReasonReact.wrapJsForReason(
    ReactNativeCalendars.Calendar,
    {
      minDate: Js_null_undefined.from_opt(minDate),
      onDayPress: Js_null_undefined.from_opt(onDayPress),
      hideArrows: Js_null_undefined.from_opt(hideArrows),
      monthFormat: Js_null_undefined.from_opt(monthFormat),
      onMonthChange: Js_null_undefined.from_opt(onMonthChange),
      hideExtraDays: Js_null_undefined.from_opt(hideExtraDays),
      disableMonthChange: Js_null_undefined.from_opt(disableMonthChange),
      firstDay: Js_null_undefined.from_opt(firstDay),
      hideDayNames: Js_null_undefined.from_opt(hideDayNames),
      markedDates: markedDates,
      markingType: Js_null_undefined.from_opt(markingType),
      style: Js_null_undefined.from_opt(style),
    },
    children
  );
}

var Calendar = /* module */ [/* make */ make];

var RNCalendars = /* module */ [/* Calendar */ Calendar];

var Font = /* module */ [];

function make$1(children) {
  return ReasonReact.wrapJsForReason(Expo.AppLoading, {}, children);
}

var AppLoading = /* module */ [/* make */ make$1];

var Permissions = /* module */ [];

var Notifications = /* module */ [];

function make$2(children) {
  return ReasonReact.wrapJsForReason(Expo.KeepAwake, {}, children);
}

var KeepAwake = /* module */ [/* make */ make$2];

var Util = /* module */ [];

var Expo$1 = /* module */ [
  /* Font */ Font,
  /* AppLoading */ AppLoading,
  /* Permissions */ Permissions,
  /* Notifications */ Notifications,
  /* KeepAwake */ KeepAwake,
  /* Util */ Util,
];

function make$3(name, size, color, children) {
  return ReasonReact.wrapJsForReason(
    VectorIcons.Feather,
    {
      name: name,
      size: size,
      color: color,
    },
    children
  );
}

var Feather = /* module */ [/* make */ make$3];

var VectorIcons$1 = /* module */ [/* Feather */ Feather];

function make$4($staropt$star, onConfirm, onCancel, mode, titleIOS, children) {
  var isVisible = $staropt$star ? $staropt$star[0] : /* false */ 0;
  return ReasonReact.wrapJsForReason(
    ReactNativeModalDatetimePicker.default,
    {
      isVisible: Js_boolean.to_js_boolean(isVisible),
      onConfirm: Js_null_undefined.from_opt(onConfirm),
      onCancel: Js_null_undefined.from_opt(onCancel),
      titleIOS: Js_null_undefined.from_opt(titleIOS),
      mode: Js_null_undefined.from_opt(mode),
    },
    children
  );
}

var DateTimePicker = /* module */ [/* make */ make$4];

var Moment = /* module */ [];

var Chroma = /* module */ [];

function make$5(text, textStyle, children) {
  return ReasonReact.wrapJsForReason(
    Ticker.default,
    {
      text: text,
      textStyle: Js_null_undefined.from_opt(textStyle),
    },
    children
  );
}

var RNTicker = /* module */ [/* make */ make$5];

exports.RNCalendars = RNCalendars;
exports.Expo = Expo$1;
exports.VectorIcons = VectorIcons$1;
exports.DateTimePicker = DateTimePicker;
exports.Moment = Moment;
exports.Chroma = Chroma;
exports.RNTicker = RNTicker;
/* expo Not a pure module */
