// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Expo = require("expo");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact = require("reason-react/src/reasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var ReactNativeCalendars = require("react-native-calendars");
var ReactNativeAnimatable = require("react-native-animatable");
var ReactNativeModalDatetimePicker = require("react-native-modal-datetime-picker");

function make(
  minDate,
  onDayPress,
  hideArrows,
  monthFormat,
  onMonthChange,
  hideExtraDays,
  disableMonthChange,
  firstDay,
  hideDayNames,
  markedDates,
  style,
  markingType,
  children
) {
  return ReasonReact.wrapJsForReason(
    ReactNativeCalendars.Calendar,
    {
      minDate: Js_null_undefined.from_opt(minDate),
      onDayPress: Js_null_undefined.from_opt(onDayPress),
      hideArrows: Js_null_undefined.from_opt(hideArrows),
      monthFormat: Js_null_undefined.from_opt(monthFormat),
      onMonthChange: Js_null_undefined.from_opt(onMonthChange),
      hideExtraDays: Js_null_undefined.from_opt(hideExtraDays),
      disableMonthChange: Js_null_undefined.from_opt(disableMonthChange),
      firstDay: Js_null_undefined.from_opt(firstDay),
      hideDayNames: Js_null_undefined.from_opt(hideDayNames),
      markedDates: Js_null_undefined.from_opt(markedDates),
      markingType: Js_null_undefined.from_opt(markingType),
      style: Js_null_undefined.from_opt(style),
    },
    children
  );
}

var Calendar = /* module */ [/* make */ make];

var RNCalendars = /* module */ [/* Calendar */ Calendar];

var Font = /* module */ [];

function make$1(children) {
  return ReasonReact.wrapJsForReason(Expo.AppLoading, {}, children);
}

var AppLoading = /* module */ [/* make */ make$1];

var Permissions = /* module */ [];

var Notifications = /* module */ [];

var Expo$1 = /* module */ [
  /* Font */ Font,
  /* AppLoading */ AppLoading,
  /* Permissions */ Permissions,
  /* Notifications */ Notifications,
];

function make$2($staropt$star, onConfirm, onCancel, mode, titleIOS, children) {
  var isVisible = $staropt$star ? $staropt$star[0] : /* false */ 0;
  return ReasonReact.wrapJsForReason(
    ReactNativeModalDatetimePicker.default,
    {
      isVisible: Js_boolean.to_js_boolean(isVisible),
      onConfirm: Js_null_undefined.from_opt(onConfirm),
      onCancel: Js_null_undefined.from_opt(onCancel),
      titleIOS: Js_null_undefined.from_opt(titleIOS),
      mode: Js_null_undefined.from_opt(mode),
    },
    children
  );
}

var DateTimePicker = /* module */ [/* make */ make$2];

var Moment = /* module */ [];

function make$3(easing, children) {
  return ReasonReact.wrapJsForReason(
    ReactNativeAnimatable.View,
    {
      easing: easing,
    },
    children
  );
}

var View = /* module */ [/* make */ make$3];

var RNAnimatable = /* module */ [/* View */ View];

exports.RNCalendars = RNCalendars;
exports.Expo = Expo$1;
exports.DateTimePicker = DateTimePicker;
exports.Moment = Moment;
exports.RNAnimatable = RNAnimatable;
/* expo Not a pure module */
