// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var variations = /* array */ [
  /* record */ [
    /* pushUps : record */ [/* sets */ 10, /* reps */ 10],
    /* sitUps : record */ [/* sets */ 10, /* reps */ 10],
    /* squats : record */ [/* sets */ 10, /* reps */ 10],
    /* run : record */ [/* distance */ 10, /* units */ "km"],
  ],
  /* record */ [
    /* pushUps : record */ [/* sets */ 5, /* reps */ 20],
    /* sitUps : record */ [/* sets */ 5, /* reps */ 20],
    /* squats : record */ [/* sets */ 5, /* reps */ 20],
    /* run : record */ [/* distance */ 10, /* units */ "km"],
  ],
  /* record */ [
    /* pushUps : record */ [/* sets */ 4, /* reps */ 25],
    /* sitUps : record */ [/* sets */ 4, /* reps */ 25],
    /* squats : record */ [/* sets */ 4, /* reps */ 25],
    /* run : record */ [/* distance */ 10, /* units */ "km"],
  ],
  /* record */ [
    /* pushUps : record */ [/* sets */ 2, /* reps */ 50],
    /* sitUps : record */ [/* sets */ 2, /* reps */ 50],
    /* squats : record */ [/* sets */ 2, /* reps */ 50],
    /* run : record */ [/* distance */ 10, /* units */ "km"],
  ],
  /* record */ [
    /* pushUps : record */ [/* sets */ 1, /* reps */ 100],
    /* sitUps : record */ [/* sets */ 1, /* reps */ 100],
    /* squats : record */ [/* sets */ 1, /* reps */ 100],
    /* run : record */ [/* distance */ 10, /* units */ "km"],
  ],
];

exports.variations = variations;
/* No side effect */
