// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Curry = require("bs-platform/lib/js/curry.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var NPMBindings = require("../../../../../config/NPMBindings.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Base = require("./styled/Base");
var Touchable = require("./styled/Touchable");

function make(disabled, left, right, onPress, children) {
  return ReasonReact.wrapJsForReason(
    Touchable.default,
    {
      disabled: Js_boolean.to_js_boolean(disabled),
      left: Js_boolean.to_js_boolean(left),
      right: Js_boolean.to_js_boolean(right),
      onPress: onPress,
    },
    children
  );
}

var Touchable$1 = /* module */ [/* make */ make];

function make$1(disabled, children) {
  return ReasonReact.wrapJsForReason(
    Base.default,
    {
      disabled: Js_boolean.to_js_boolean(disabled),
    },
    children
  );
}

var Base$1 = /* module */ [/* make */ make$1];

var Styled = /* module */ [/* Touchable */ Touchable$1, /* Base */ Base$1];

var component = ReasonReact.statelessComponent("IntensityButton");

function make$2(onPress, action, disabled, _) {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    var match = +(action === "decrement");
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      make(
        disabled,
        +(action === "decrement"),
        +(action === "increment"),
        onPress,
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            make$1(
              disabled,
              /* array */ [
                ReasonReact.element(
                  /* None */ 0,
                  /* None */ 0,
                  Curry._4(
                    NPMBindings.VectorIcons[/* Feather */ 0][/* make */ 0],
                    match !== 0 ? "arrow-left" : "arrow-right",
                    18,
                    "white",
                    /* array */ []
                  )
                ),
              ]
            )
          ),
        ]
      )
    );
  };
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, function(jsProps) {
  return make$2(
    jsProps.onPress,
    jsProps.action,
    jsProps.disabled,
    /* array */ []
  );
});

exports.Styled = Styled;
exports.component = component;
exports.make = make$2;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
