// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Container = require("./Container");
var ReasonReact = require("reason-react/src/reasonReact.js");
var BarContainer = require("./BarContainer");

function make(parentContainerWidth, children) {
  return ReasonReact.wrapJsForReason(
    Container.default,
    {
      parentContainerWidth: parentContainerWidth,
    },
    children
  );
}

var Container$1 = /* module */ [/* make */ make];

function make$1(children) {
  return ReasonReact.wrapJsForReason(BarContainer.default, {}, children);
}

var BarContainer$1 = /* module */ [/* make */ make$1];

exports.Container = Container$1;
exports.BarContainer = BarContainer$1;
/* ./Container Not a pure module */
