// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Bar = require("./Bar");
var Title = require("./Title");
var Amount = require("./Amount");
var Container = require("./Container");
var ReasonReact = require("reason-react/src/reasonReact.js");
var BarContainer = require("./BarContainer");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function make(parentContainerWidth, children) {
  return ReasonReact.wrapJsForReason(
    Container.default,
    {
      parentContainerWidth: parentContainerWidth,
    },
    children
  );
}

var Container$1 = /* module */ [/* make */ make];

function make$1(onLayout, children) {
  return ReasonReact.wrapJsForReason(
    BarContainer.default,
    {
      onLayout: Js_null_undefined.from_opt(onLayout),
    },
    children
  );
}

var BarContainer$1 = /* module */ [/* make */ make$1];

function make$2(width, children) {
  return ReasonReact.wrapJsForReason(
    Bar.default,
    {
      width: width,
    },
    children
  );
}

var Bar$1 = /* module */ [/* make */ make$2];

function make$3(children) {
  return ReasonReact.wrapJsForReason(Title.default, {}, children);
}

var Title$1 = /* module */ [/* make */ make$3];

function make$4(children) {
  return ReasonReact.wrapJsForReason(Amount.default, {}, children);
}

var Amount$1 = /* module */ [/* make */ make$4];

exports.Container = Container$1;
exports.BarContainer = BarContainer$1;
exports.Bar = Bar$1;
exports.Title = Title$1;
exports.Amount = Amount$1;
/* ./Bar Not a pure module */
