// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var WorkoutStore = require("./WorkoutStore");

var workout = WorkoutStore.default;

exports.workout = workout;
/* workout Not a pure module */
