// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Block = require("bs-platform/lib/js/block.js");
var Colors = require("../../../../config/Colors.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var NPMBindings = require("../../../../config/NPMBindings.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Container = require("./styled/Container");
var Style$BsReactNative = require("bs-react-native/src/style.js");

function make(children) {
  return ReasonReact.wrapJsForReason(Container.default, {}, children);
}

var Container$1 = /* module */ [/* make */ make];

var Styled = /* module */ [/* Container */ Container$1];

var component = ReasonReact.statelessComponent("Timer");

function make$1(time, _) {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      make(
        /* array */ [
          ReasonReact.element(
            /* None */ 0,
            /* None */ 0,
            NPMBindings.RNTicker[/* make */ 0](
              Pervasives.string_of_int(time),
              /* Some */ [
                Style$BsReactNative.style(
                  /* :: */ [
                    Style$BsReactNative.fontFamily("InterReg"),
                    /* :: */ [
                      Style$BsReactNative.backgroundColor("transparent"),
                      /* :: */ [
                        Style$BsReactNative.fontSize(
                          /* Float */ Block.__(0, [64])
                        ),
                        /* :: */ [
                          Style$BsReactNative.color(Colors.spotiBlack),
                          /* :: */ [
                            Style$BsReactNative.textAlign(/* Center */ 3),
                            /* [] */ 0,
                          ],
                        ],
                      ],
                    ],
                  ]
                ),
              ],
              /* array */ []
            )
          ),
        ]
      )
    );
  };
  return newrecord;
}

exports.Styled = Styled;
exports.component = component;
exports.make = make$1;
/* component Not a pure module */
