// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Title = require("./Title");
var Container = require("./Container");
var HeroImage = require("./HeroImage");
var ReasonReact = require("reason-react/src/reasonReact.js");
var Description = require("./Description");
var TextContentContainer = require("./TextContentContainer");

function make(source, resizeMode, children) {
  return ReasonReact.wrapJsForReason(
    HeroImage.default,
    {
      source: source,
      resizeMode: resizeMode,
    },
    children
  );
}

var HeroImage$1 = /* module */ [/* make */ make];

function make$1(children) {
  return ReasonReact.wrapJsForReason(Container.default, {}, children);
}

var Container$1 = /* module */ [/* make */ make$1];

function make$2(children) {
  return ReasonReact.wrapJsForReason(
    TextContentContainer.default,
    {},
    children
  );
}

var TextContentContainer$1 = /* module */ [/* make */ make$2];

function make$3(children) {
  return ReasonReact.wrapJsForReason(Title.default, {}, children);
}

var Title$1 = /* module */ [/* make */ make$3];

function make$4(children) {
  return ReasonReact.wrapJsForReason(Description.default, {}, children);
}

var Description$1 = /* module */ [/* make */ make$4];

exports.HeroImage = HeroImage$1;
exports.Container = Container$1;
exports.TextContentContainer = TextContentContainer$1;
exports.Title = Title$1;
exports.Description = Description$1;
/* ./Title Not a pure module */
