name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          cache: npm
      - run: npm ci
      - run: npx expo-doctor
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test -- --ci
